name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Render Deploy Hook (Backend)
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
        
    - name: Trigger Render Deploy Hook (Frontend)
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}